// Replace this single value after App Store Connect provides the public listing URL.
// A production build refuses to ship while the placeholder ID is still present.
export const siteConfig = {
  siteOrigin: "https://getlenspin.com",
  appStoreUrl: "https://apps.apple.com/app/id0000000000",
  appStorePlaceholderId: "0000000000",
  // Apple-hosted artwork generated by App Store Marketing Tools. Do not restyle or redraw it.
  appStoreBadgeUrl: "https://tools.applemediaservices.com/api/badges/download-on-the-app-store/black/en-us?size=250x83"
};
